version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/healthCheck.sh
      runas: ec2-user