version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

hooks:
  ApplicationStart:
    - location: scripts/executeDeploy.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: scripts/healthCheck.sh
      timeout: 60
      runas: ec2-user