version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

hooks:
  ApplicationStart:
    - location: scripts/execute-deploy.sh
      timeout: 180
      runas: ec2-user
  ValidateService:
    - location: scripts/healthCheck.sh
      timeout: 180
      runas: ec2-user