version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: scripts/deploy.sh > /home/ec2-user/deploy.log
      timeout: 180