version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - mv ./build/libs/*.jar ./
artifacts:
  files:
    - appspec.yml
    - scripts/**
    - springboot-deploy*.jar

cache:
  paths:
    - '/root/.gradle/caches/**/*'