version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
      - mkdir ./jar/
      - mv ./build/libs/*.jar ./jar/

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - jar/**

cache:
  paths:
    - '/root/.m2/**/*'