version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
      - mv ./build/libs/*.jar ./

artifacts:
  files:
    - *.jar
    - appspec.yml
    - scripts/run.sh
    - scripts/deploy.sh

cache:
  paths:
    - '/root/.m2/**/*'