version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/

cache:
  paths:
    - '/root/.m2/**/*'