version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build

  post_build:
    commands:
      - echo Before Build $(basename ./build/libs/*.jar)
      - mv ./build/libs/*.jar ./
      - echo Before Build $(basename ./build/libs/*.jar)
artifacts:
  files:
    - appspec.yml
    - scripts/**
    - s**.jar

cache:
  paths:
    - '/root/.gradle/caches/**/*'